version: "3.8"
services:
  database:
    build:
      context: ./
      dockerfile: ./Dockerfile.db
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"


